export const routes = [
  {
    path: "/",
    name: "Home",
    showInNavbar: true,
    icon: null,
    protected: false,
    role: ["user", "admin"],
  },
  {
    path: "/about",
    name: "About",
    showInNavbar: true,
    icon: null,
    protected: false,
    role: ["user", "admin"],
  },
  {
    path: "/portfolio",
    name: "Portfolio",
    showInNavbar: true,
    icon: null,
    protected: false,
    role: ["user", "admin"],
  },
  {
    path: "/portfolio/$slug",
    name: "PortfolioDetails",
    icon: null,
    showInNavbar: false,
    protected: false,
    role: ["user", "admin"],
  },
  {
    path: "/blog",
    name: "Blog",
    showInNavbar: true,
    icon: null,
    protected: false,
    role: ["user", "admin"],
  },
  {
    path: "/blog/$slug",
    name: "BlogDetails",
    icon: null,
    showInNavbar: false,
    protected: false,
    role: ["user", "admin"],
  },
  {
    path: "/contact",
    name: "Contact",
    showInNavbar: true,
    icon: null,
    protected: false,
    role: ["user", "admin"],
  },

  // ----- Dashboard (flat structure) -----
  {
    path: "/dashboard",
    name: "Dashboard",
    layout: "DashboardLayout",
    showInNavbar: false,
    // protected: true,
    // role: ["admin"],
  },
  {
    path: "/dashboard/services",
    name: "Services",
    layout: "DashboardLayout",
    showInNavbar: false,
    icon: null,
    // protected: true,
    // role: ["admin"],
  },
  {
    path: "/dashboard/blogs",
    name: "BlogsSettings",
    layout: "DashboardLayout",
    showInNavbar: false,
    icon: null,
    // protected: true,
    // role: ["admin"],
  },
];

