export const routes = [
  {
    path: "/",
    name: "Home",
    showInNavbar: true,
    icon: null,
    protected: false,
    role: ["user", "admin"],
  },
  {
    path: "/about",
    name: "About",
    showInNavbar: true,
    icon: null,
    protected: false,
    role: ["user", "admin"],
  },
  {
    path: "/portfolio",
    name: "Portfolio",
    showInNavbar: true,
    icon: null,
    protected: false,
    role: ["user", "admin"],
  },
  {
    path: "/portfolio/$slug",
    name: "PortfolioDetails",
    icon: null,
    showInNavbar: false,
    protected: false,
    role: ["user", "admin"],
  },
  {
    path: "/contact",
    name: "Contact",
    showInNavbar: true,
    icon: null,
    protected: false,
    role: ["user", "admin"],
  },
];
